### ISSUE TITLE
Seems to be busted by Meteor 1.0.2

### ISSUE THREAD

**Issue by alpjor** [mquandalle/meteor-harmony#37]
Can't seem to start my project now. :(

```command
Why-Not:storm alpjor$ meteor --settings config/settings.json 
[[[[[ ~/Documents/Code/bolt/storm ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
                                              
/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
TypeError: Cannot read property 'length' of undefined
    at Map.size (/Users/alpjor/.meteor/packages/mquandalle_harmony/.1.3.79.vsi28k++os+web.browser+web.cordova/plugin.compileHarmony.os/npm/compileHarmony/node_modules/traceur/bin/traceur.js:1254:27)
    at /Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:719:27
    at initialize (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:317:38)
    at /Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:716:3
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:793:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:8:54)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:74:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/behavior.js:9:23)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/emissary.js:4:13)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/node_modules/emissary/lib/emissary.js:14:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/file.js:12:18)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/file.js:384:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:203:18)
    at Object.<anonymous> (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.watch (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/safe-pathwatcher.js:27:5)
    at [object Object]._.extend._watchFileOrDirectory (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:417:35)
    at /Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:384:14
    at Function._.each._.forEach (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend._startFileWatches (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:379:7)
    at new Watcher (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:309:8)
    at [object Object]._.extend._runOnce (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:653:23)
    at [object Object]._.extend._fiber (/Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:758:28)
    at /Users/alpjor/.meteor/packages/meteor-tool/.1.0.37.1ovh56a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:365:12
Why-Not:storm alpjor$ mate /Users/alpjor/.meteor/packages/mquandalle_harmony/.1.3.79.vsi28k++os+web.browser+web.cordova/plugin.compileHarmony.os/npm/compileHarmony/node_modules/traceur/bin/traceur.js
```

**Comment by seeekr** [comment]
For reference until this is fixed without monkey-patching: The files in meteor 1.0.2.1 are now these 2 -

`~/.meteor/packages/meteor-tool/.1.0.38.1bth24m++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/harmony-collections/harmony-collections.js


~/.meteor/packages/meteor-tool/.1.0.38.1bth24m++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js`

I tried to make a `sed` script for automatic replacement of stuff but my shell-fu was not enough to wrestle the special character handling in bash and sed to the ground...

**Comment by tomitrescak** [comment]
So, what to do now guys? How can I make it run? This is a great showstopper for me now :/ I changed the proposed lines to what you have suggested but I still receive the error ;/

**Comment by seeekr** [comment]
@tomitrescak I only meant to give the updated file names since they changed between Meteor versions 1.0.2 and 1.0.2.1, apparently.

**Comment by christianbundy** [comment]
I asked that over at google/traceur-compiler#1613, I just haven't had time to implement it yet.

**Comment by tomitrescak** [comment]
Guys, new version of Meteor is out there, problem remains. Thank god for the fix you found, but a permanent solution would be fantastic.

**Comment by epaminond** [comment]
Are there any news on this issue? Pull request by @Termina1 seems to be still open.

**Comment by alpjor** [comment]
I am also really looking forward to a more permeant fix. Any idea why the pull request is stalled?

**Comment by Termina1** [comment]
May be someone could contact @Benvie to ask him merge this pull request? His account email is not working.

**Comment by christianbundy** [comment]
I found another email address for @Benvie, hopefully that one goes through.

Our other option would be to fork his project and get pull requests merged [here](https://github.com/atom/emissary/blob/708a91a85bdec2f21757e6c06ef2fbb9d15477cc/package.json#L35) and [here](https://github.com/atom/property-accessors/blob/ecc333ba1b6989e63c4bbd17701a3bee913d6fc9/package.json#L32) to use our new implementation. I don't really like the idea of forking the project unless absolutely necessary, but it's an option.

**Comment by mquandalle** [comment]
https://github.com/Benvie/harmony-collections haven't be updated for about a whole year, so we should consider @Termina1 PR won't be merged anytime soon. Maybe we could replace this lib by https://github.com/WebReflection/es6-collections (not tested) instead of maintaining our own fork?

**Comment by Termina1** [comment]
So, I just decided to update ```emissary``` and ```property-accessor``` to get rid of ```harmony-collections```. Pull requests are here https://github.com/atom/property-accessors/pull/5/files and here https://github.com/atom/emissary/pull/10/files

**Comment by Termina1** [comment]
Created pull request (https://github.com/atom/node-pathwatcher/pull/58), so it is the last thing. After this is merged, we just need to wait until new meteor version, where will be new pathwatcher module.

**Comment by nicksergeant** [comment]
I'm seeing the same error on Meteor 1.0.3.2:

```
> meteor
[[[[[ ~/Code/siftie ]]]]]

=> Started proxy.
=> Started MongoDB.

/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                                                throw(ex);
                                                      ^
TypeError: Cannot read property 'length' of undefined
  at Map.size (/Users/Nick/.meteor/packages/mquandalle_harmony/.1.3.79.3uufil++os+web.browser+web.cordova/plugin.compileHarmony.os/npm/compileHarmony/node_modules/traceur/bin/traceur.js:1254:27)
  at /Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:719:27
  at initialize (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:317:38)
  at /Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:716:3
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/node_modules/harmony-collections/harmony-collections.js:793:2)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:8:54)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:74:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/behavior.js:9:23)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/behavior.js:120:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/helpers.js:5:14)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/helpers.js:55:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/emissary.js:4:13)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/node_modules/emissary/lib/emissary.js:14:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/lib/file.js:12:18)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/lib/file.js:384:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/lib/main.js:203:18)
  at Object.<anonymous> (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-pathwatcher-tweaks/lib/main.js:207:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/Nick/.meteor/packages/meteorhacks_npm/.1.2.2.1mhfgu6++os+web.browser+web.cordova/plugin.initializing-npm-support.os/npm/initializing-npm-support/node_modules/node-echo/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.files.pathwatcherWatch (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/files.js:1230:21)
  at Object.watch (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/safe-pathwatcher.js:33:23)
  at [object Object]._.extend._watchFileOrDirectory (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:414:35)
  at /Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:381:14
  at Function._.each._.forEach (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at [object Object]._.extend._startFileWatches (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:376:7)
  at new Watcher (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/watch.js:307:8)
  at [object Object]._.extend._runOnce (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:663:23)
  at [object Object]._.extend._fiber (/Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:771:28)
  at /Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:366:12


> meteor list
accounts-password          1.0.6  Password support for accounts
accounts-ui                1.1.4  Simple templates to add login widgets to an app
email                      1.0.5  Send email messages
erasaur:meteor-lodash      3.5.0  Wrapper for Lo-Dash v3.5.0
fourseven:scss             2.0.1_2  Style with attitude. Sass and SCSS support for Met...
houston:admin              2.0.3  A zero-config Meteor Admin
iron:router                1.0.7  Routing specifically designed for Meteor
meteor-platform            1.2.1  Include a standard set of Meteor packages in your app
meteorhacks:kadira         2.19.6  Performance Monitoring for Meteor
meteorhacks:npm            1.2.2  Use npm modules with your Meteor App
mquandalle:harmony         1.3.79  JavaScript.next-to-JavaScript-of-today compiler
npm-container              1.0.0+ Contains all your npm dependencies
reywood:publish-composite  1.3.5  Publish a set of related documents from multiple col...
spiderable                 1.0.6  Makes the application crawlable to web spiders

+ These packages are built locally from source.

> meteor --version
Meteor 1.0.3.2
```

**Comment by Termina1** [comment]
Because fixes did not land in this version. If you use master everything should be ok

**Comment by tomitrescak** [comment]
I had to go with grigio:babel in the end ...

**Comment by nicksergeant** [comment]
@tomitrescak thanks! Babel works much better.

**Comment by mquandalle** [comment]
Should we “officialy” encourage users to use babel?

**Comment by Termina1** [comment]
@mquandalle I don't think so, there should be always an alternative.

**Comment by epaminond** [comment]
An error seems to be fixed on `1.0.4.1` release.

**Comment by jakobdamjensen** [comment]
yeah it seems to work fine on 1.0.4.1... Great

**Comment by mquandalle** [comment]
Good to hear, let me close this issue
